# Generated by Django 2.0 on 2019-12-23 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(null=True, upload_to='uploads/logos/')),
                ('first_name', models.CharField(default='', max_length=200, null=True)),
                ('last_name', models.CharField(default='', max_length=200, null=True)),
                ('phone', models.IntegerField(default='', null=True)),
                ('email', models.EmailField(default='', max_length=200, null=True)),
                ('details', models.TextField(default='', null=True)),
                ('date_joined', models.TextField(default='', null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
