# Generated by Django 2.0 on 2019-12-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_student_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_occuring_word', models.CharField(default='', max_length=200, null=True)),
                ('vowel_a', models.IntegerField(default=0, null=True)),
                ('vowel_e', models.IntegerField(default=0, null=True)),
                ('vowel_i', models.IntegerField(default=0, null=True)),
                ('vowel_o', models.IntegerField(default='', null=True)),
                ('vowel_u', models.IntegerField(default='', null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('artist', models.CharField(default='', max_length=200, null=True)),
                ('lyrics', models.TextField(default='', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lyric',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Student'),
        ),
    ]
