# Generated by Django 2.0 on 2019-12-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191224_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lyrics_count',
            field=models.IntegerField(null=True),
        ),
    ]
