# Generated by Django 2.0 on 2019-01-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190104_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image1',
            field=models.FileField(upload_to='media/uploads/carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image2',
            field=models.FileField(upload_to='media/uploads/carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image3',
            field=models.FileField(upload_to='media/uploads/carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='media/uploads/course_imgs'),
        ),
        migrations.AlterField(
            model_name='global',
            name='logo',
            field=models.FileField(upload_to='media/uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.FileField(upload_to='media/uploads/testimonial_imgs'),
        ),
    ]
