# Generated by Django 2.0 on 2019-01-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190104_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='about',
        ),
        migrations.AddField(
            model_name='global',
            name='about_body',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='global',
            name='about_text',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='global',
            name='about_title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image1',
            field=models.FileField(null=True, upload_to='uploads/carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image2',
            field=models.FileField(null=True, upload_to='uploads/carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image3',
            field=models.FileField(null=True, upload_to='uploads/carousel_imgs/'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='message1',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='message2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='message3',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='center_section',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='center_section',
            name='title',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='center_section_cards',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='center_section_cards',
            name='title',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/course_imgs/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='global',
            name='facebook',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='global',
            name='insta',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='global',
            name='location',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='global',
            name='logo',
            field=models.FileField(null=True, upload_to='uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='global',
            name='phone',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='global',
            name='twitter',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='take_away',
            name='text',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='first_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='last_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
