# Generated by Django 2.0 on 2019-01-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190104_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='about_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
