# Generated by Django 2.0 on 2019-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190104_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='header',
            field=models.FileField(null=True, upload_to='uploads/course_imgs/'),
        ),
    ]
