# Generated by Django 2.0 on 2019-01-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
