# Generated by Django 2.0 on 2019-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190104_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='email',
            field=models.EmailField(default='', max_length=200, null=True),
        ),
    ]
