# Generated by Django 2.0 on 2019-01-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_global_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='starts_here',
            field=models.BooleanField(default=True),
        ),
    ]
