# Generated by Django 2.0 on 2019-01-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190105_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center_section_cards',
            old_name='course',
            new_name='center_section',
        ),
    ]
