# Generated by Django 2.0 on 2019-01-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190105_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255, null=True)),
                ('email', models.EmailField(default='', max_length=200, null=True)),
                ('phone', models.CharField(default='', max_length=255, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('coupon', models.CharField(default='', max_length=255, null=True)),
                ('payment', models.IntegerField(choices=[(1, 'Full payment'), (2, 'Installment'), (3, 'Others')], default=1)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='main.Course')),
            ],
        ),
    ]
