# Generated by Django 2.0 on 2019-12-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='global',
            options={'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
    ]
